Repository googleapis/java-functions, pull requests merged in 2020-09, with the labels that each got.

#28 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudfunctions, cla: yes, context: full

#29 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#31 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#32 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#33 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudfunctions, automerge, cla: yes

#34 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#35 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#37 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
