Repository googleapis/java-functions, pull requests merged in 2020-11, with the labels that each got.

#69 chore: fix versions.txt manifest
  versions.txt
Labels: api: cloudfunctions, cla: yes

#76 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#77 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#78 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#79 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#82 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#87 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#88 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#90 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#91 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full, samples
