Repository googleapis/java-functions, pull requests merged in 2020-10, with the labels that each got.

#38 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#39 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: api: cloudfunctions, cla: yes

#48 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#49 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#50 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#51 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#52 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#61 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#62 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#63 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#41 feat: promote to 1.0.0
  .repo-metadata.json
Labels: api: cloudfunctions, cla: yes

#66 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#68 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#70 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
