Repository googleapis/java-functions, pull requests merged in 2021-05, with the labels that each got.

#196 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: none

#197 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudfunctions, automerge, cla: yes

#198 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudfunctions, automerge, cla: yes

#199 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#206 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#207 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#208 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#210 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#213 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#215 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#219 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#220 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes
