Repository googleapis/java-functions, pull requests merged in 2021-01, with the labels that each got.

#115 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, cla: yes

#116 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#117 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudfunctions, automerge, cla: yes

#118 chore: update gapic-generator-java to 0.0.18
  google-cloud-functions/src/main/java/com/google/cloud/functions/v1/CloudFunctionsServiceClient.java
  google-cloud-functions/src/main/java/com/google/cloud/functions/v1/stub/CloudFunctionsServiceStub.java
  google-cloud-functions/src/main/java/com/google/cloud/functions/v1/stub/CloudFunctionsServiceStubSettings.java
  google-cloud-functions/src/main/java/com/google/cloud/functions/v1/stub/GrpcCloudFunctionsServiceCallableFactory.java
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#124 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudfunctions, automerge, cla: yes, context: full

#126 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: cloudfunctions, automerge, cla: yes
